/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/_layout'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authInitAuthRouteImport } from './routes/(auth)/init-auth'
import { Route as protectedLayoutUserManagementRouteImport } from './routes/(protected)/_layout/user-management'
import { Route as protectedLayoutProfileRouteImport } from './routes/(protected)/_layout/profile'
import { Route as protectedLayoutDownloadsRouteImport } from './routes/(protected)/_layout/downloads'
import { Route as protectedLayoutDownloadCreateRouteImport } from './routes/(protected)/_layout/download-create'
import { Route as protectedLayoutDashboardRouteImport } from './routes/(protected)/_layout/dashboard'
import { Route as protectedLayoutDownloadEditDownloadIdRouteImport } from './routes/(protected)/_layout/download-edit.$downloadId'
import { Route as protectedLayoutDownloadDetailDownloadIdRouteImport } from './routes/(protected)/_layout/download-detail.$downloadId'

const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authInitAuthRoute = authInitAuthRouteImport.update({
  id: '/(auth)/init-auth',
  path: '/init-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutUserManagementRoute =
  protectedLayoutUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutProfileRoute = protectedLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => protectedLayoutRoute,
} as any)
const protectedLayoutDownloadsRoute =
  protectedLayoutDownloadsRouteImport.update({
    id: '/downloads',
    path: '/downloads',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutDownloadCreateRoute =
  protectedLayoutDownloadCreateRouteImport.update({
    id: '/download-create',
    path: '/download-create',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutDashboardRoute =
  protectedLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutDownloadEditDownloadIdRoute =
  protectedLayoutDownloadEditDownloadIdRouteImport.update({
    id: '/download-edit/$downloadId',
    path: '/download-edit/$downloadId',
    getParentRoute: () => protectedLayoutRoute,
  } as any)
const protectedLayoutDownloadDetailDownloadIdRoute =
  protectedLayoutDownloadDetailDownloadIdRouteImport.update({
    id: '/download-detail/$downloadId',
    path: '/download-detail/$downloadId',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/init-auth': typeof authInitAuthRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof protectedLayoutDashboardRoute
  '/download-create': typeof protectedLayoutDownloadCreateRoute
  '/downloads': typeof protectedLayoutDownloadsRoute
  '/profile': typeof protectedLayoutProfileRoute
  '/user-management': typeof protectedLayoutUserManagementRoute
  '/download-detail/$downloadId': typeof protectedLayoutDownloadDetailDownloadIdRoute
  '/download-edit/$downloadId': typeof protectedLayoutDownloadEditDownloadIdRoute
}
export interface FileRoutesByTo {
  '/init-auth': typeof authInitAuthRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof protectedLayoutDashboardRoute
  '/download-create': typeof protectedLayoutDownloadCreateRoute
  '/downloads': typeof protectedLayoutDownloadsRoute
  '/profile': typeof protectedLayoutProfileRoute
  '/user-management': typeof protectedLayoutUserManagementRoute
  '/download-detail/$downloadId': typeof protectedLayoutDownloadDetailDownloadIdRoute
  '/download-edit/$downloadId': typeof protectedLayoutDownloadEditDownloadIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/init-auth': typeof authInitAuthRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(protected)/_layout': typeof protectedLayoutRouteWithChildren
  '/(protected)/_layout/dashboard': typeof protectedLayoutDashboardRoute
  '/(protected)/_layout/download-create': typeof protectedLayoutDownloadCreateRoute
  '/(protected)/_layout/downloads': typeof protectedLayoutDownloadsRoute
  '/(protected)/_layout/profile': typeof protectedLayoutProfileRoute
  '/(protected)/_layout/user-management': typeof protectedLayoutUserManagementRoute
  '/(protected)/_layout/download-detail/$downloadId': typeof protectedLayoutDownloadDetailDownloadIdRoute
  '/(protected)/_layout/download-edit/$downloadId': typeof protectedLayoutDownloadEditDownloadIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/init-auth'
    | '/sign-in'
    | '/dashboard'
    | '/download-create'
    | '/downloads'
    | '/profile'
    | '/user-management'
    | '/download-detail/$downloadId'
    | '/download-edit/$downloadId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/init-auth'
    | '/sign-in'
    | '/dashboard'
    | '/download-create'
    | '/downloads'
    | '/profile'
    | '/user-management'
    | '/download-detail/$downloadId'
    | '/download-edit/$downloadId'
  id:
    | '__root__'
    | '/(auth)/init-auth'
    | '/(auth)/sign-in'
    | '/(protected)/_layout'
    | '/(protected)/_layout/dashboard'
    | '/(protected)/_layout/download-create'
    | '/(protected)/_layout/downloads'
    | '/(protected)/_layout/profile'
    | '/(protected)/_layout/user-management'
    | '/(protected)/_layout/download-detail/$downloadId'
    | '/(protected)/_layout/download-edit/$downloadId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authInitAuthRoute: typeof authInitAuthRoute
  authSignInRoute: typeof authSignInRoute
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/init-auth': {
      id: '/(auth)/init-auth'
      path: '/init-auth'
      fullPath: '/init-auth'
      preLoaderRoute: typeof authInitAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/user-management': {
      id: '/(protected)/_layout/user-management'
      path: '/user-management'
      fullPath: '/user-management'
      preLoaderRoute: typeof protectedLayoutUserManagementRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/profile': {
      id: '/(protected)/_layout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof protectedLayoutProfileRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/downloads': {
      id: '/(protected)/_layout/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof protectedLayoutDownloadsRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/download-create': {
      id: '/(protected)/_layout/download-create'
      path: '/download-create'
      fullPath: '/download-create'
      preLoaderRoute: typeof protectedLayoutDownloadCreateRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/dashboard': {
      id: '/(protected)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedLayoutDashboardRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/download-edit/$downloadId': {
      id: '/(protected)/_layout/download-edit/$downloadId'
      path: '/download-edit/$downloadId'
      fullPath: '/download-edit/$downloadId'
      preLoaderRoute: typeof protectedLayoutDownloadEditDownloadIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
    '/(protected)/_layout/download-detail/$downloadId': {
      id: '/(protected)/_layout/download-detail/$downloadId'
      path: '/download-detail/$downloadId'
      fullPath: '/download-detail/$downloadId'
      preLoaderRoute: typeof protectedLayoutDownloadDetailDownloadIdRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedLayoutDashboardRoute: typeof protectedLayoutDashboardRoute
  protectedLayoutDownloadCreateRoute: typeof protectedLayoutDownloadCreateRoute
  protectedLayoutDownloadsRoute: typeof protectedLayoutDownloadsRoute
  protectedLayoutProfileRoute: typeof protectedLayoutProfileRoute
  protectedLayoutUserManagementRoute: typeof protectedLayoutUserManagementRoute
  protectedLayoutDownloadDetailDownloadIdRoute: typeof protectedLayoutDownloadDetailDownloadIdRoute
  protectedLayoutDownloadEditDownloadIdRoute: typeof protectedLayoutDownloadEditDownloadIdRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedLayoutDashboardRoute: protectedLayoutDashboardRoute,
  protectedLayoutDownloadCreateRoute: protectedLayoutDownloadCreateRoute,
  protectedLayoutDownloadsRoute: protectedLayoutDownloadsRoute,
  protectedLayoutProfileRoute: protectedLayoutProfileRoute,
  protectedLayoutUserManagementRoute: protectedLayoutUserManagementRoute,
  protectedLayoutDownloadDetailDownloadIdRoute:
    protectedLayoutDownloadDetailDownloadIdRoute,
  protectedLayoutDownloadEditDownloadIdRoute:
    protectedLayoutDownloadEditDownloadIdRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authInitAuthRoute: authInitAuthRoute,
  authSignInRoute: authSignInRoute,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
