/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as protectedLayoutRouteImport } from './routes/(protected)/_layout'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authInitAuthRouteImport } from './routes/(auth)/init-auth'
import { Route as protectedLayoutDashboardRouteImport } from './routes/(protected)/_layout/dashboard'

const protectedLayoutRoute = protectedLayoutRouteImport.update({
  id: '/(protected)/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authInitAuthRoute = authInitAuthRouteImport.update({
  id: '/(auth)/init-auth',
  path: '/init-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedLayoutDashboardRoute =
  protectedLayoutDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => protectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/init-auth': typeof authInitAuthRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof protectedLayoutDashboardRoute
}
export interface FileRoutesByTo {
  '/init-auth': typeof authInitAuthRoute
  '/sign-in': typeof authSignInRoute
  '/dashboard': typeof protectedLayoutDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)/init-auth': typeof authInitAuthRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(protected)/_layout': typeof protectedLayoutRouteWithChildren
  '/(protected)/_layout/dashboard': typeof protectedLayoutDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/init-auth' | '/sign-in' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/init-auth' | '/sign-in' | '/dashboard'
  id:
    | '__root__'
    | '/(auth)/init-auth'
    | '/(auth)/sign-in'
    | '/(protected)/_layout'
    | '/(protected)/_layout/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authInitAuthRoute: typeof authInitAuthRoute
  authSignInRoute: typeof authSignInRoute
  protectedLayoutRoute: typeof protectedLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(protected)/_layout': {
      id: '/(protected)/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof protectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/init-auth': {
      id: '/(auth)/init-auth'
      path: '/init-auth'
      fullPath: '/init-auth'
      preLoaderRoute: typeof authInitAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/_layout/dashboard': {
      id: '/(protected)/_layout/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof protectedLayoutDashboardRouteImport
      parentRoute: typeof protectedLayoutRoute
    }
  }
}

interface protectedLayoutRouteChildren {
  protectedLayoutDashboardRoute: typeof protectedLayoutDashboardRoute
}

const protectedLayoutRouteChildren: protectedLayoutRouteChildren = {
  protectedLayoutDashboardRoute: protectedLayoutDashboardRoute,
}

const protectedLayoutRouteWithChildren = protectedLayoutRoute._addFileChildren(
  protectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authInitAuthRoute: authInitAuthRoute,
  authSignInRoute: authSignInRoute,
  protectedLayoutRoute: protectedLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
