packages:
  - apps/*
  - packages/*
catalog:
  dotenv: ^17.2.2
  zod: ^4.1.13
  typescript: ^5
  "@types/bun": ^1.3.6
  "@trpc/server": ^11.7.2
  better-auth: ^1.4.9
  "@trpc/client": ^11.7.2
  drizzle-orm: ^0.45.1
  "@types/pg": ^8.15.6
